In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as np
import seaborn as sns

In [29]:
df=pd.read_csv('/content/coffee-dataset.csv')
print(df)

    100g_USD  rating         roast
0      14.32      95  Medium-Light
1       9.05      94  Medium-Light
2       4.70      92  Medium-Light
3       4.19      92  Medium-Light
4       4.85      94        Medium
..       ...     ...           ...
94      6.76      92  Medium-Light
95      4.04      92  Medium-Light
96      4.63      92  Medium-Light
97      4.12      94  Medium-Light
98      5.00      93  Medium-Light

[99 rows x 3 columns]


In [30]:
X= df.iloc[: , :-1].values
print(X)
Y= df.iloc[:,-1:].values
print(Y)

[[14.32 95.  ]
 [ 9.05 94.  ]
 [ 4.7  92.  ]
 [ 4.19 92.  ]
 [ 4.85 94.  ]
 [ 5.14 93.  ]
 [ 3.97 93.  ]
 [ 5.14 93.  ]
 [ 5.29 93.  ]
 [ 3.76 94.  ]
 [ 7.2  95.  ]
 [ 3.89 93.  ]
 [ 2.82 92.  ]
 [ 5.73 90.  ]
 [ 6.87 92.  ]
 [ 6.87 91.  ]
 [11.45 95.  ]
 [ 4.41 87.  ]
 [ 5.28 93.  ]
 [33.05 97.  ]
 [ 4.6  95.  ]
 [ 5.29 92.  ]
 [ 3.89 95.  ]
 [ 3.98 93.  ]
 [ 3.98 94.  ]
 [ 4.65 94.  ]
 [ 5.58 93.  ]
 [ 5.88 92.  ]
 [ 3.5  89.  ]
 [ 5.86 93.  ]
 [ 4.41 92.  ]
 [ 5.58 93.  ]
 [ 4.7  93.  ]
 [ 4.98 92.  ]
 [ 4.98 89.  ]
 [ 7.35 93.  ]
 [ 4.41 93.  ]
 [ 5.   93.  ]
 [ 9.7  93.  ]
 [ 6.47 95.  ]
 [ 4.41 94.  ]
 [ 5.88 93.  ]
 [12.35 93.  ]
 [ 8.44 94.  ]
 [16.17 96.  ]
 [ 7.35 95.  ]
 [32.63 94.  ]
 [ 5.66 96.  ]
 [11.02 95.  ]
 [19.82 95.  ]
 [ 5.86 95.  ]
 [ 4.98 93.  ]
 [16.56 95.  ]
 [13.   93.  ]
 [17.7  93.  ]
 [ 8.8  92.  ]
 [ 4.98 91.  ]
 [ 5.57 96.  ]
 [ 4.63 91.  ]
 [26.46 95.  ]
 [17.64 93.  ]
 [12.13 92.  ]
 [13.23 92.  ]
 [ 5.   93.  ]
 [ 5.28 94.  ]
 [ 5.88 95.  ]
 [ 3.54 93

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
 le_y= LabelEncoder()
 Y=le_y.fit_transform(Y)
 print(Y)

[3 3 3 3 1 0 3 3 3 1 1 3 3 1 3 3 3 3 3 3 3 2 3 3 3 3 0 3 3 3 3 0 0 3 1 3 3
 3 0 3 3 0 3 0 3 3 3 3 3 3 3 3 3 3 1 3 1 3 0 3 0 0 3 0 0 3 3 3 3 3 1 3 0 3
 3 3 3 0 0 3 3 0 3 3 2 3 3 1 3 3 2 0 0 0 3 3 3 3 3]


/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [33]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LinearRegression
X_train,X_test,y_train,y_test = train_test_split(X,Y, test_size = 0.20)


In [34]:
X_train

array([[ 4.98, 89.  ],
       [ 5.  , 92.  ],
       [ 5.86, 95.  ],
       [ 3.54, 92.  ],
       [ 3.97, 93.  ],
       [ 5.29, 92.  ],
       [ 4.7 , 92.  ],
       [11.45, 95.  ],
       [ 7.35, 92.  ],
       [ 4.63, 92.  ],
       [ 4.12, 93.  ],
       [ 7.05, 92.  ],
       [ 5.14, 93.  ],
       [ 9.7 , 93.  ],
       [ 6.47, 95.  ],
       [ 5.28, 93.  ],
       [23.81, 95.  ],
       [ 4.11, 90.  ],
       [ 3.98, 93.  ],
       [14.32, 95.  ],
       [ 4.98, 93.  ],
       [ 4.98, 91.  ],
       [13.  , 90.  ],
       [ 3.54, 93.  ],
       [ 4.65, 94.  ],
       [ 5.88, 95.  ],
       [ 5.57, 96.  ],
       [17.64, 93.  ],
       [ 5.88, 92.  ],
       [ 4.41, 87.  ],
       [ 4.25, 93.  ],
       [ 4.56, 92.  ],
       [ 4.63, 91.  ],
       [ 5.14, 93.  ],
       [12.13, 92.  ],
       [ 9.05, 94.  ],
       [32.63, 94.  ],
       [ 7.05, 91.  ],
       [ 4.85, 94.  ],
       [ 4.41, 92.  ],
       [ 3.89, 95.  ],
       [ 4.99, 94.  ],
       [ 2.82, 92.  ],
       [ 5.

In [35]:
y_train

array([1, 0, 3, 3, 3, 2, 3, 3, 3, 3, 3, 1, 3, 0, 3, 3, 0, 1, 3, 3, 3, 1,
       3, 3, 3, 3, 3, 0, 3, 3, 0, 3, 0, 0, 0, 3, 3, 3, 1, 3, 3, 0, 3, 0,
       0, 3, 0, 3, 2, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 0,
       3, 3, 3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 1])

In [36]:
lr = LinearRegression()
cofee_model = lr.fit(X_train, y_train)
predictions = cofee_model.predict(X_test)

In [37]:
print(predictions)
print(y_test)

[2.03387827 2.1719904  2.06686954 2.20086101 2.12449068 2.05923407
 2.31491254 2.04080346 2.16809953 2.29515016 2.01221485 2.35410308
 2.06180882 2.11388876 2.10234677 2.02269142 2.82127153 1.96404142
 2.08009843 2.10358976]
[3 1 3 2 3 3 3 3 3 3 3 3 3 0 3 3 3 3 3 3]


In [38]:
from sklearn.metrics import r2_score
r2_score(y_test, predictions)


-0.5332237935515896