In [19]:
import numpy as np
import pandas as pd


In [20]:
df=pd.read_csv('/content/coffee-dataset.csv')
print(df)

    100g_USD  rating         roast
0      14.32      95  Medium-Light
1       9.05      94  Medium-Light
2       4.70      92  Medium-Light
3       4.19      92  Medium-Light
4       4.85      94        Medium
..       ...     ...           ...
94      6.76      92  Medium-Light
95      4.04      92  Medium-Light
96      4.63      92  Medium-Light
97      4.12      94  Medium-Light
98      5.00      93  Medium-Light

[99 rows x 3 columns]


In [21]:
df['roast'].value_counts()

roast
Medium-Light    68
Light           19
Medium           9
Medium-Dark      3
Name: count, dtype: int64

In [22]:
x=df.iloc[:,0:2].values
y=df.iloc[:,2].values
from sklearn.preprocessing import LabelEncoder
labelencoder_y= LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [23]:
y

array([3, 3, 3, 3, 1, 0, 3, 3, 3, 1, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 2,
       3, 3, 3, 3, 0, 3, 3, 3, 3, 0, 0, 3, 1, 3, 3, 3, 0, 3, 3, 0, 3, 0,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 0, 3, 0, 0, 3, 0, 0, 3,
       3, 3, 3, 3, 1, 3, 0, 3, 3, 3, 3, 0, 0, 3, 3, 0, 3, 3, 2, 3, 3, 1,
       3, 3, 2, 0, 0, 0, 3, 3, 3, 3, 3])

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [25]:
x_train

array([[19.82, 95.  ],
       [ 3.89, 94.  ],
       [ 4.41, 94.  ],
       [ 4.12, 94.  ],
       [ 5.29, 93.  ],
       [ 5.14, 93.  ],
       [ 9.2 , 95.  ],
       [ 4.04, 92.  ],
       [ 5.66, 96.  ],
       [13.  , 90.  ],
       [11.02, 95.  ],
       [ 5.14, 93.  ],
       [ 4.99, 94.  ],
       [ 5.28, 93.  ],
       [ 4.65, 94.  ],
       [16.56, 95.  ],
       [13.  , 93.  ],
       [26.46, 95.  ],
       [ 3.54, 93.  ],
       [ 5.88, 93.  ],
       [ 5.  , 93.  ],
       [ 5.86, 95.  ],
       [ 7.05, 91.  ],
       [ 5.58, 93.  ],
       [ 4.25, 93.  ],
       [ 4.98, 93.  ],
       [ 3.98, 93.  ],
       [ 4.12, 93.  ],
       [ 9.05, 94.  ],
       [ 5.29, 92.  ],
       [90.83, 93.  ],
       [ 4.7 , 93.  ],
       [22.49, 95.  ],
       [ 4.6 , 95.  ],
       [ 5.07, 93.  ],
       [ 5.58, 93.  ],
       [ 4.85, 94.  ],
       [16.17, 96.  ],
       [ 4.11, 90.  ],
       [32.63, 94.  ],
       [ 4.56, 92.  ],
       [ 5.28, 94.  ],
       [ 4.7 , 92.  ],
       [11.

In [10]:
x_train.size

138

In [11]:
x_test.size

60

In [12]:
y_train.size

69

In [13]:
y_test.size

30

In [15]:
from sklearn.linear_model import LogisticRegression


In [16]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
y_pred= logmodel.predict(x_test)

In [26]:
y_pred
np.sort(y_pred)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3])

In [27]:
y_test
np.sort(y_test)

array([0, 0, 0, 0, 0, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3])

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
confusion_matrix(y_test,y_pred)

array([[ 0,  0,  5],
       [ 0,  0,  3],
       [ 0,  0, 22]])

In [30]:
logmodel.score(x_test,y_test)

0.7

In [31]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [32]:
y_pred_knn=classifier_knn.predict(x_test)

In [33]:
y_pred_knn

array([3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 0])

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_matrix(y_test,y_pred_knn)

array([[ 0,  0,  5],
       [ 0,  0,  3],
       [ 1,  1, 20]])

In [36]:
classifier_knn.score(x_test,y_test)

0.6666666666666666

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.6666666666666666

In [39]:
from sklearn.naive_bayes import GaussianNB

In [42]:
classifier_nb= GaussianNB()

In [44]:
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [45]:
y_pred= classifier_nb.predict(x_test)

In [46]:
y_pred

array([0, 3, 1, 1, 0, 1, 3, 3, 3, 3, 1, 3, 1, 0, 3, 3, 3, 1, 0, 1, 3, 0,
       3, 0, 1, 3, 1, 0, 0, 0])

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.6666666666666666

In [48]:
confusion_matrix(y_test,y_pred)

array([[ 3,  2,  0],
       [ 0,  1,  2],
       [ 6,  6, 10]])

In [49]:
classifier_nb.score(x_test,y_test)

0.4666666666666667